### ISSUE TITLE
Type consistency relation example

### ISSUE THREAD

**Issue by Javran** [Javran/adding-gradual-types#2]
The type consistency relation discussed in Gradual Typing for Functional Languages contains type consistency for lambda calculus, and I want to give an example that does not belong to this relation, a straightforward one is `(dyn, dyn)` vs. `dyn -> dyn`, but pairs are outside of lambda calculus. I'm wondering what to do: (1) extend the rule to support tuples, (2) Church encoding, not sure how though (3) find another example within lambda calculus

**Comment by dvanhorn** [comment]
If you only have `?` and `->` then everything is consistent, but you always have some ground type (e.g. `bool`) in the original type system (and therefore in the gradual system), at which point it is easy to make examples: `bool !~ ? -> ?`.

**Comment by Javran** [comment]
@dvanhorn got it, thanks!
